# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('total_discount', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('total_price', models.CharField(max_length=50)),
                ('total_discounts', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('line_items', models.ManyToManyField(to='shopify.Item')),
            ],
            options={
                'ordering': ['order_number'],
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['first_name'],
                'verbose_name_plural': 'Shipping',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ManyToManyField(to='shopify.Shipping'),
        ),
    ]
