# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='line_items',
            field=models.ManyToManyField(blank=True, null=True, to='shopify.Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ManyToManyField(blank=True, null=True, to='shopify.Shipping'),
        ),
    ]
